services:
  frontend:
    build:
      context: .
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    profiles:
      - front
  backend:
    build:
      context: server/
    container_name: backend
    ports:
      - "3001:3001"
    restart: always
    profiles:
      - back