
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grpzctxumndpwdwzgzqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdycHpjdHh1bW5kcHdkd3pnenF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Njc3NTUsImV4cCI6MjA1OTM0Mzc1NX0.au6WCg30IA9bx4-5MdapzytvS-AJoet5dFyPOIzHopw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type definitions for service requests to avoid TypeScript errors
// This is a workaround until the types.ts file is automatically regenerated
export type ServiceRequest = {
  id: string;
  service_id: string;
  service_name: string;
  client_id: string;
  client_name: string;
  request_date: string;
  status: string;
  admin_notes?: string | null;
  updated_at: string;
}

// Helper function to safely access the service_requests table
export const serviceRequestsTable = () => {
  return supabase.from('service_requests');
};

