// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvispmmrfcjtjefimbfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2aXNwbW1yZmNqdGplZmltYmZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTg1NjQsImV4cCI6MjA1OTI3NDU2NH0.aFtDPyo1ISQ14yhUziLPxzdMILxL6xrp6eA8pKW-J6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);